//
//  cpu_handlers.c
//  plasmvm
//
//  Created by Noah Wooten on 2/2/22.
//

#include "cpu.h"

DeclInstruction(SET);
DeclInstruction(LDWM);
DeclInstruction(STWM);
DeclInstruction(LDBM);
DeclInstruction(STBM);
DeclInstruction(OR);
DeclInstruction(AND);
DeclInstruction(XOR);
DeclInstruction(NOT);
DeclInstruction(ADD);
DeclInstruction(SUB);
DeclInstruction(MUL);
DeclInstruction(DIV);
DeclInstruction(SETI);
DeclInstruction(LDWMI);
DeclInstruction(STWMI);
DeclInstruction(LDBMI);
DeclInstruction(STBMI);
DeclInstruction(ORI);
DeclInstruction(ANDI);
DeclInstruction(XORI);
DeclInstruction(ADDI);
DeclInstruction(SUBI);
DeclInstruction(MULI);
DeclInstruction(DIVI);
DeclInstruction(SL);
DeclInstruction(SR);
DeclInstruction(SLI);
DeclInstruction(SRI);
DeclInstruction(SA);
DeclInstruction(SP);
DeclInstruction(SAI);
DeclInstruction(GO);
DeclInstruction(ENT);
DeclInstruction(RT);
DeclInstruction(RTF);
DeclInstruction(RTFI);
DeclInstruction(GOI);
DeclInstruction(ENTI);
DeclInstruction(CMP);
DeclInstruction(CMPI);
DeclInstruction(GOF);
DeclInstruction(ENTF);
DeclInstruction(ENTFI);
DeclInstruction(ENTFII);
DeclInstruction(GOFI);
DeclInstruction(GOFII);
DeclInstruction(NEG);
DeclInstruction(EIH);
DeclInstruction(DIH);
DeclInstruction(HLT);
DeclInstruction(INT);
DeclInstruction(INTI);
DeclInstruction(HND);
DeclInstruction(HNDI);
DeclInstruction(HNDII);
DeclInstruction(SPA);
DeclInstruction(SPG);
DeclInstruction(SAA);
DeclInstruction(SAG);
DeclInstruction(LDSD);
DeclInstruction(LDSDI);
DeclInstruction(STSD);
DeclInstruction(LDVM);
DeclInstruction(LDVMI);
DeclInstruction(STVM);
DeclInstruction(SPN);
DeclInstruction(MSP);
DeclInstruction(SSP);
DeclInstruction(ASP);
DeclInstruction(SPB);
DeclInstruction(SAB);
DeclInstruction(SAII);
DeclInstruction(INC);
DeclInstruction(DEC);
DeclInstruction(SBN);
DeclInstruction(SBN);
DeclInstruction(IOB);
DeclInstruction(IIB);
DeclInstruction(IOW);
DeclInstruction(IIW);
DeclInstruction(IOS);
DeclInstruction(IIS);
DeclInstruction(LDQM);
DeclInstruction(LDQMI);
DeclInstruction(LDHM);
DeclInstruction(LDHMI);
DeclInstruction(STQM);
DeclInstruction(STQMI);
DeclInstruction(STHM);
DeclInstruction(STHMI);
DeclInstruction(STWMII);
DeclInstruction(STHMII);
DeclInstruction(STQMII);
DeclInstruction(STBMII);
DeclInstruction(GFCPS);
DeclInstruction(SFDP);
DeclInstruction(CFDP);
DeclInstruction(TFRX);
DeclInstruction(CFRI);
DeclInstruction(CFFI);
DeclInstruction(LSFR);
DeclInstruction(LDFR);
DeclInstruction(FABS);
DeclInstruction(FABST);
DeclInstruction(FADD);
DeclInstruction(FADDT);
DeclInstruction(FSUB);
DeclInstruction(FSUBT);
DeclInstruction(FMUL);
DeclInstruction(FMULT);
DeclInstruction(FDIV);
DeclInstruction(FDIVT);
DeclInstruction(FMOD);
DeclInstruction(FMODT);
DeclInstruction(FSIN);
DeclInstruction(FSINT);
DeclInstruction(FCOS);
DeclInstruction(FCOST);
DeclInstruction(FTAN);
DeclInstruction(FTANT);
DeclInstruction(FSEC);
DeclInstruction(FSECT);
DeclInstruction(FCSC);
DeclInstruction(FCSCT);
DeclInstruction(FCOT);
DeclInstruction(FCOTT);
DeclInstruction(FEXP);
DeclInstruction(FEXPI);
DeclInstruction(FEXPI);
DeclInstruction(FEXPT);
DeclInstruction(FEXPI);
DeclInstruction(FEXPIT);
DeclInstruction(FNSIN);
DeclInstruction(FNSINT);
DeclInstruction(FNCOS);
DeclInstruction(FNCOST);
DeclInstruction(FNTAN);
DeclInstruction(FNTANT);
DeclInstruction(FNSEC);
DeclInstruction(FNCSC);
DeclInstruction(FNCOT);
DeclInstruction(FNSECT);
DeclInstruction(FNCSCT);
DeclInstruction(FNCOTT);
DeclInstruction(FINC);
DeclInstruction(FDEC);
DeclInstruction(FNEG);
DeclInstruction(F1OX);
DeclInstruction(FFCT);
DeclInstruction(FFSF);
DeclInstruction(FAIF);
DeclInstruction(FSIF);
DeclInstruction(FMIF);
DeclInstruction(FDIF);
DeclInstruction(FMODIF);
DeclInstruction(FAIFI);
DeclInstruction(FSIFI);
DeclInstruction(FMIFI);
DeclInstruction(FDIFI);
DeclInstruction(FMODIFI);
DeclInstruction(FLOG2);
DeclInstruction(FLOG10);
DeclInstruction(FLOGE);
DeclInstruction(FE10X);
DeclInstruction(FNOP);
DeclInstruction(F2XM1);
DeclInstruction(FCMPFR);
DeclInstruction(FCMPFF);
DeclInstruction(FCMPFRI);
DeclInstruction(FCMPFFI);
DeclInstruction(FEEX);
DeclInstruction(CFFT);
DeclInstruction(FSQRT);
DeclInstruction(FCBRT);
DeclInstruction(FNRTI);
DeclInstruction(FLOG2I);
DeclInstruction(FLOG10I);
DeclInstruction(FLOGEI);
DeclInstruction(FLOG2R);
DeclInstruction(FLOG10R);
DeclInstruction(FLOGER);
DeclInstruction(FNRTX);

void(*InstructionHandlers[256])(void) = {
	ListInstruction(SET),
	ListInstruction(LDWM),
	ListInstruction(STWM),
	ListInstruction(LDBM),
	ListInstruction(STBM),
	ListInstruction(OR),
	ListInstruction(AND),
	ListInstruction(XOR),
	ListInstruction(NOT),
	ListInstruction(ADD),
	ListInstruction(SUB),
	ListInstruction(MUL),
	ListInstruction(DIV),
	ListInstruction(SETI),
	ListInstruction(LDWMI),
	ListInstruction(STWMI),
	ListInstruction(LDBMI),
	ListInstruction(STBMI),
	ListInstruction(ORI),
	ListInstruction(ANDI),
	ListInstruction(XORI),
	ListInstruction(ADDI),
	ListInstruction(SUBI),
	ListInstruction(MULI),
	ListInstruction(DIVI),
	ListInstruction(SL),
	ListInstruction(SR),
	ListInstruction(SLI),
	ListInstruction(SRI),
	ListInstruction(SA),
	ListInstruction(SP),
	ListInstruction(SAI),
	ListInstruction(GO),
	ListInstruction(ENT),
	ListInstruction(RT),
	ListInstruction(RTF),
	ListInstruction(RTFI),
	ListInstruction(GOI),
	ListInstruction(ENTI),
	ListInstruction(CMP),
	ListInstruction(CMPI),
	ListInstruction(GOF),
	ListInstruction(ENTF),
	ListInstruction(ENTFI),
	ListInstruction(ENTFII),
	ListInstruction(GOFI),
	ListInstruction(GOFII),
	ListInstruction(NEG),
	ListInstruction(EIH),
	ListInstruction(DIH),
	ListInstruction(HLT),
	ListInstruction(INT),
	ListInstruction(INTI),
	ListInstruction(HND),
	ListInstruction(HNDI),
	ListInstruction(HNDII),
	ListInstruction(SPA),
	ListInstruction(SPG),
	ListInstruction(SAA),
	ListInstruction(SAG),
	ListInstruction(LDSD),
	ListInstruction(LDSDI),
	ListInstruction(STSD),
	ListInstruction(LDVM),
	ListInstruction(LDVMI),
	ListInstruction(STVM),
	ListInstruction(SPN),
	ListInstruction(MSP),
	ListInstruction(SSP),
	ListInstruction(ASP),
	ListInstruction(SPB),
	ListInstruction(SAB),
	ListInstruction(SAII),
	ListInstruction(INC),
	ListInstruction(DEC),
	ListInstruction(SBN),
	ListInstruction(IOB),
	ListInstruction(IIB),
	ListInstruction(IOW),
	ListInstruction(IIW),
	ListInstruction(IOS),
	ListInstruction(IIS),
	ListInstruction(LDQM),
	ListInstruction(LDQMI),
	ListInstruction(LDHM),
	ListInstruction(LDHMI),
	ListInstruction(STQM),
	ListInstruction(STQMI),
	ListInstruction(STHM),
	ListInstruction(STHMI),
	ListInstruction(STWMII),
	ListInstruction(STHMII),
	ListInstruction(STQMII),
	ListInstruction(STBMII),
	ListInstruction(GFCPS),
	ListInstruction(SFDP),
	ListInstruction(CFDP),
	ListInstruction(TFRX),
	ListInstruction(CFRI),
	ListInstruction(CFFI),
	ListInstruction(LSFR),
	ListInstruction(LDFR),
	ListInstruction(FABS),
	ListInstruction(FABST),
	ListInstruction(FADD),
	ListInstruction(FADDT),
	ListInstruction(FSUB),
	ListInstruction(FSUBT),
	ListInstruction(FMUL),
	ListInstruction(FMULT),
	ListInstruction(FDIV),
	ListInstruction(FDIVT),
	ListInstruction(FMOD),
	ListInstruction(FMODT),
	ListInstruction(FSIN),
	ListInstruction(FSINT),
	ListInstruction(FCOS),
	ListInstruction(FCOST),
	ListInstruction(FTAN),
	ListInstruction(FTANT),
	ListInstruction(FSEC),
	ListInstruction(FSECT),
	ListInstruction(FCSC),
	ListInstruction(FCSCT),
	ListInstruction(FCOT),
	ListInstruction(FCOTT),
	ListInstruction(FEXP),
	ListInstruction(FEXPI),
	ListInstruction(FEXPT),
	ListInstruction(FEXPIT),
	ListInstruction(FNSIN),
	ListInstruction(FNSINT),
	ListInstruction(FNCOS),
	ListInstruction(FNCOST),
	ListInstruction(FNTAN),
	ListInstruction(FNTANT),
	ListInstruction(FNSEC),
	ListInstruction(FNCSC),
	ListInstruction(FNCOT),
	ListInstruction(FNSECT),
	ListInstruction(FNCSCT),
	ListInstruction(FNCOTT),
	ListInstruction(FINC),
	ListInstruction(FDEC),
	ListInstruction(FNEG),
	ListInstruction(F1OX),
	ListInstruction(FFCT),
	ListInstruction(FFSF),
	ListInstruction(FAIF),
	ListInstruction(FSIF),
	ListInstruction(FMIF),
	ListInstruction(FDIF),
	ListInstruction(FMODIF),
	ListInstruction(FAIFI),
	ListInstruction(FSIFI),
	ListInstruction(FMIFI),
	ListInstruction(FDIFI),
	ListInstruction(FMODIFI),
	ListInstruction(FLOG2),
	ListInstruction(FLOG10),
	ListInstruction(FLOGE),
	ListInstruction(FE10X),
	ListInstruction(FNOP),
	ListInstruction(F2XM1),
	ListInstruction(FCMPFR),
	ListInstruction(FCMPFF),
	ListInstruction(FCMPFRI),
	ListInstruction(FCMPFFI),
	ListInstruction(FEEX),
	ListInstruction(CFFT),
	ListInstruction(FSQRT),
	ListInstruction(FCBRT),
	ListInstruction(FNRTI),
	ListInstruction(FLOG2I),
	ListInstruction(FLOG10I),
	ListInstruction(FLOGEI),
	ListInstruction(FLOG2R),
	ListInstruction(FLOG10R),
	ListInstruction(FLOGER),
	ListInstruction(FNRTX),
};
