name: macOS Build

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: get sdl2
      run: |
        brew install SDL2
        brew install SDL2_ttf
    - uses: actions/checkout@v2
    - name: make
      run: make
